export const storeProducts = [
  {
    id: 1,
    title: "Watch 1",
    img: require("../images/watch1.jpg"),
    price: 2000,
    company: "RD",
    info: "First watch in the goddamn store!!",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Watch 2",
    img: require("../images/watch2.jpg"),
    price: 3000,
    company: "RD",
    info: "second watch in the goddamn store!!",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Watch 3",
    img: require("../images/watch3.jpg"),
    price: 4000,
    company: "RD",
    info: "third watch in the goddamn store!!",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Watch 4",
    img: require("../images/watch4.jpg"),
    price: 5000,
    company: "RD",
    info: "fourth watch in the goddamn store!!",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Watch 5",
    img: require("../images/watch5.jpg"),
    price: 6000,
    company: "RD",
    info: "fifth watch in the goddamn store!!",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Watch 6",
    img: require("../images/watch6.jpg"),
    price: 7000,
    company: "RD",
    info: "sixth watch in the goddamn store!!",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 1,
  title: "Watch 7",
  img: require("../images/watch7.jpg"),
  price: 7000,
  company: "RD",
  info:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  inCart: false,
  count: 0,
  total: 0,
};
